// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class Banca : BaseEntity
{
    public int IdCurso { get; set; }

    public virtual Curso IdCursoNavigation { get; set; }

    public virtual ICollection<ProfessorBanca> ProfessorBanca { get; set; } = new List<ProfessorBanca>();
}