// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class Calendario : BaseEntity
{
    //public int Id { get; set; }

    public int IdCurso { get; set; }

    public DateTime? DataInicio { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }

    public virtual Curso IdCursoNavigation { get; set; }
}