// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class ProfessorBanca
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public int IdBanca { get; set; }

    public virtual Banca IdBancaNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}