// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SistemaGestaoTcc.Core.Enums;

namespace SistemaGestaoTcc.Core.Models;

public partial class Projeto : BaseEntity
{

    public Projeto(string nome, string descricao)
    {
        Nome = nome;
        Descricao = descricao;
        DataInicio = DateTime.Now;
        DataFim = DateTime.Now;
        Estado = (int?)StatusProjeto.Created;
        Publicado = false;
        Aprovado = false;
    }

    public string Nome { get; set; }

    public string Descricao { get;  set; }

    public DateTime? DataInicio { get;  set; }

    public DateTime? DataFim { get; set; }

    public bool? Publicado { get;  set; }

    public bool? Aprovado { get;  set; }

    public int? Estado { get;  set; }

    public virtual ICollection<Convite> Convite { get; set; } = new List<Convite>();

    public virtual ICollection<Nota> Nota { get; set; } = new List<Nota>();

    public virtual ICollection<ProjetoArquivo> ProjetoArquivo { get; set; } = new List<ProjetoArquivo>();

    public virtual ICollection<ProjetoComentario> ProjetoComentario { get; set; } = new List<ProjetoComentario>();

    public virtual ICollection<UsuarioProjeto> UsuarioProjeto { get; set; } = new List<UsuarioProjeto>();
}