// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SistemaGestaoTcc.Core.Models;

public partial class SistemaTccContext : DbContext
{
    public SistemaTccContext()
    {
    }

    public SistemaTccContext(DbContextOptions<SistemaTccContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Banca> Banca { get; set; }

    public virtual DbSet<Calendario> Calendario { get; set; }

    public virtual DbSet<Convite> Convite { get; set; }

    public virtual DbSet<Curso> Curso { get; set; }

    public virtual DbSet<Nota> Nota { get; set; }

    public virtual DbSet<ProfessorBanca> ProfessorBanca { get; set; }

    public virtual DbSet<Projeto> Projeto { get; set; }

    public virtual DbSet<ProjetoArquivo> ProjetoArquivo { get; set; }

    public virtual DbSet<ProjetoComentario> ProjetoComentario { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioProjeto> UsuarioProjeto { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Banca>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Banca__3214EC07216A1A56");

            entity.HasIndex(e => e.IdCurso, "Banca_FKIndex1");

            entity.HasOne(d => d.IdCursoNavigation).WithMany(p => p.Banca)
                .HasForeignKey(d => d.IdCurso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Banca__IdCurso__412EB0B6");
        });

        modelBuilder.Entity<Calendario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Calendar__3214EC079053AAED");

            entity.HasIndex(e => e.IdCurso, "Calendario_FKIndex1");

            entity.Property(e => e.DataInicio).HasColumnType("datetime");
            entity.Property(e => e.Descricao)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Titulo)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.IdCursoNavigation).WithMany(p => p.Calendario)
                .HasForeignKey(d => d.IdCurso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Calendari__IdCur__45F365D3");
        });

        modelBuilder.Entity<Convite>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Convite__3214EC07E946B505");

            entity.HasIndex(e => e.IdProjeto, "Convite_FKIndex1");

            entity.HasIndex(e => e.IdUsuario, "Convite_FKIndex2");

            entity.Property(e => e.DataEnvio).HasColumnType("datetime");
            entity.Property(e => e.DataExpira).HasColumnType("datetime");

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.Convite)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Convite__IdProje__5FB337D6");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Convite)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Convite__IdUsuar__60A75C0F");
        });

        modelBuilder.Entity<Curso>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Curso__3214EC07A2F6EBB6");

            entity.Property(e => e.Nome)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Nota>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Nota__3214EC07E5499FCB");

            entity.HasIndex(e => e.IdUsuario, "Nota_FKIndex1");

            entity.HasIndex(e => e.IdProjeto, "Nota_FKIndex2");

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.Nota)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Nota__IdProjeto__6754599E");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Nota)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Nota__IdUsuario__66603565");
        });

        modelBuilder.Entity<ProfessorBanca>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Professo__3214EC07C961204A");

            entity.HasIndex(e => e.IdBanca, "ProfessorBanca_FKIndex1");

            entity.HasIndex(e => e.IdProfessor, "ProfessorBanca_FKIndex2");

            entity.HasOne(d => d.IdBancaNavigation).WithMany(p => p.ProfessorBanca)
                .HasForeignKey(d => d.IdBanca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Professor__IdBan__6D0D32F4");

            entity.HasOne(d => d.IdProfessorNavigation).WithMany(p => p.ProfessorBanca)
                .HasForeignKey(d => d.IdProfessor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Professor__IdPro__6E01572D");
        });

        modelBuilder.Entity<Projeto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Projeto__3214EC07A234990B");

            entity.Property(e => e.DataFim).HasColumnType("datetime");
            entity.Property(e => e.DataInicio).HasColumnType("datetime");
            entity.Property(e => e.Descricao)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ProjetoArquivo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoA__3214EC07F3A31F12");

            entity.HasIndex(e => e.IdProjeto, "ProjetoArquivo_FKIndex1");

            entity.HasIndex(e => e.IdUsuario, "ProjetoArquivo_FKIndex2");

            entity.Property(e => e.CriadoEm).HasColumnType("datetime");
            entity.Property(e => e.DiretorioArquivo)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoArquivo)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoAr__IdPro__59063A47");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.ProjetoArquivo)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoAr__IdUsu__59FA5E80");
        });

        modelBuilder.Entity<ProjetoComentario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoC__3214EC078C55A598");

            entity.HasIndex(e => e.IdProjeto, "ProjetoComentario_FKIndex1");

            entity.HasIndex(e => e.IdUsuario, "ProjetoComentario_FKIndex2");

            entity.Property(e => e.Conteudo)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.CriadoEm).HasColumnType("datetime");

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoComentario)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoCo__IdPro__52593CB8");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.ProjetoComentario)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoCo__IdUsu__534D60F1");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuario__3214EC073804DA99");

            entity.Property(e => e.Email)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Papel)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Senha)
                .HasMaxLength(300)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UsuarioProjeto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UsuarioP__3214EC076231A295");

            entity.HasIndex(e => e.IdUsuario, "UsuarioProjeto_FKIndex1");

            entity.HasIndex(e => e.IdProjeto, "UsuarioProjeto_FKIndex2");

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.UsuarioProjeto)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsuarioPr__IdPro__4CA06362");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioProjeto)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsuarioPr__IdUsu__4BAC3F29");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}