// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class Usuario : BaseEntity
{
    public Usuario(int idCurso, string nome, string email, string senha, string papel, int? periodo)
    {
        IdCurso = idCurso;
        Nome = nome;
        Email = email;
        Senha = senha;
        Papel = papel;
        Periodo = periodo;
    }

    public int IdCurso { get; set; }

    public string Imagem { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string Senha { get; set; }

    public string Papel { get; set; }

    public int? Periodo { get; set; }

    public virtual ICollection<Convite> Convite { get; set; } = new List<Convite>();

    public virtual Curso IdCursoNavigation { get; set; }

    public virtual ICollection<Nota> Nota { get; set; } = new List<Nota>();

    public virtual ICollection<ProfessorBanca> ProfessorBanca { get; set; } = new List<ProfessorBanca>();

    //public virtual ICollection<ProjetoArquivo> ProjetoArquivo { get; set; } = new List<ProjetoArquivo>();

    public virtual ICollection<ProjetoComentario> ProjetoComentario { get; set; } = new List<ProjetoComentario>();

    public virtual ICollection<UsuarioProjeto> UsuarioProjeto { get; set; } = new List<UsuarioProjeto>();

    public void Update(int idCurso, string nome)
    {
        Nome = nome;
        IdCurso = idCurso;
    }
}