// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class Usuario
{
    //CONFERIR PORQUE TA PEDINDO 2 CONSTRUTORES
    public Usuario(string nome, string email, string papel1, string papel2, string passwordHash)
    {
        Nome = nome;
        Email = email;
    }

    public Usuario(int id, string nome, string email, string senha, string papel, int? periodo)
    {
        Id = id;
        Nome = nome;
        Email = email;
        Senha = senha;
        Papel = papel;
        Periodo = periodo;
    }

    public int Id { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string Senha { get; set; }

    public string Papel { get; set; }

    public int? Periodo { get; set; }

    public virtual ICollection<Convite> Convite { get; set; } = new List<Convite>();

    public virtual ICollection<Nota> Nota { get; set; } = new List<Nota>();

    public virtual ICollection<ProfessorBanca> ProfessorBanca { get; set; } = new List<ProfessorBanca>();

    public virtual ICollection<ProjetoArquivo> ProjetoArquivo { get; set; } = new List<ProjetoArquivo>();

    public virtual ICollection<ProjetoComentario> ProjetoComentario { get; set; } = new List<ProjetoComentario>();

    public virtual ICollection<UsuarioProjeto> UsuarioProjeto { get; set; } = new List<UsuarioProjeto>();

}